# Site settings
title: Matthew Castrillon-Madrigal
email: thecodermatt@protonmail.com
url: https://matthewcm.github.io
description: "Matthew Castrillon-Madrigal's Personal Portfolio"
keywords: "your keywords, separated by commas"
skills: "Web Developer - Digital Artist - Tech Blogger"
meta_author: Castrillon-Madrigal Matthew

collections:
  projects:
    output: true

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

favicon: /img/favicon.png


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fbde44ff
  primary-rgb: "24,88,156"
  secondary: f65058ff
  secondary-dark: 28334aff

# Footer settings
footer:
  social: Around the Web
  copyright: Matthew Castrillon-Madrigal


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/matthewC_M
  - title: github
    url: http://github.com/matthewcm


# Build settings
markdown: kramdown
permalink: pretty
